import math

WIDTH, HEIGHT = 1600, 900
FPS=60
FONT="Bitstream"

PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.002
PLAYER_ANGLE_SPEED = 0.0001

FOV = math.pi / 3
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20
CAMERA_PLANE_DIST = (WIDTH/2) / math.tan(FOV/2)
SCALE = WIDTH // NUM_RAYS

